steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/flask-app-436123/frontend:${SHORT_SHA}'
      - '-f'
      - './Dockerfile',
      - '.'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/flask-app-436123/frontend-service:${SHORT_SHA}'

logsBucket: 'gs://gcp-app-logs'
