steps:

    # step 1: build the both images backend and frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA', './frontend' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA', './backend' ]

    # step 2: push both images to the GCR repository
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/GCP-Web-Application/frontend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/GCP-Web-Application/backend:$SHORT_SHA' ]

logsBucket: 'gs://gcp-app-logs'