apiVersion: v1
kind: Namespace
metadata:
  name: frontend-ns
  labels:
    name: frontend-ns
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  FLASK_SERVER_URL: "http://flask-backend-service.backend-ns.svc:5000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
      - name: node-frontend
        image: gcr.io/flask-app-436123/frontend:v1.0
        env:
        - name: FLASK_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: FLASK_SERVER_URL
        ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: node-frontend-service
spec:
  selector:
    app: node-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: NodePort
